title: 20 GHz VNA Project
description: >-
  A home-built vector network analyzer (VNA) project targeting 20 GHz.
  Build notes, measurements, photos and downloadable raw data files.
author: patryksi11
baseurl: "/20ghz-vna-blog"
url: "https://patryksi11.github.io"
permalink: /blog/:title/
markdown: kramdown

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post